### ISSUE TITLE
Build Graphite and Grafana on a monitoring server

### ISSUE THREAD

**Issue by preaction** [cpan-testers/cpantesters-deploy#2]
We should have a monitoring server with the Graphite time series database and the Grafana web application installed. This should be another server outside our current data centers, if possible. This server will collect statistics, display them in a useful status page, and also be used for monitoring and alerting.

**Comment by zdykstra** [comment]
I just finished deploying a Graphite/Carbon stack in Go. I can write up some quick documentation on it if you'd like, it's vastly easier to install than the original Python stack, and more performant as well.

**Comment by preaction** [comment]
Yeah, that'd be great! Right now I'm stuck in the maelstrom of compiling Go 1.8 for Grafana on OpenBSD 6.0 (since it comes with 1.6). Might as well use that as much as possible since I've got to build it ;)

**Comment by zdykstra** [comment]
The stack in it's minimal form consists of the following components:

[go-carbon](https://github.com/lomik/go-carbon)
[carbonzipper](https://github.com/dgryski/carbonzipper)
[carbonapi](https://github.com/dgryski/carbonapi)


go-carbon ingests the metrics via 2003/tcp and writes them out to disk. It also runs a carbonserver instance, that is used to read whisper files off of disk for queries. This can be bound to any port, it's arbitrary. 

carbonzipper sits in front of one or more go-carbon carbonservers and requests metrics. If you have a few graphite servers, this bridges all of them and finds the metric(s) for you. Bind it to a port, and point it to the carbonserver:port(s) you're running.

carbonapi is where you send graphite queries. It in turn talks to carbonzipper to get the metrics off the backend(s). 

So the flow for ingest is:

client -> go-carbon 2003/tcp

The flow for queries is:

grafana -> carbonapi 80/tcp -> carbonzipper 8081/tcp -> [ carbonserver1:81 carbonserver2:81 ..]

If you want the graphite data stored on multiple servers, then I'd suggest using carbon-c-relay to sit in front of carbonapi and duplicate your metrics out to multiple go-carbon instances.

**Comment by preaction** [comment]
We'll just have the one server, I don't think this is going to have too much in the way of use (but it's a tiny server, so better performance is good).

If I only have the one server, can I get away with only go-carbon?

**Comment by preaction** [comment]
Upon some reading it looks like, no, indeed the minimal stack you mentioned is even for only one server.

**Comment by zdykstra** [comment]
You might be able to get away with just go-carbon and carbonapi, but I'm
not sure. Go-carbon can't do any rendering or computation of metrics, so
carbonapi is still required for that. Then it's just a question of making
those two mesh with out carbonzipper, and I haven't tried that.

**Comment by preaction** [comment]
Using an OpenBSD 6.0 virtual machine with 2G of memory, I was able to build the Go 1.8 package from the ports snapshot. I also built the go-bootstrap 1.4.3 package (as the go-1.8 package claims to require it). Using this, I was able to install Grafana from source using [Grafana build from source instructions](http://docs.grafana.org/project/building_from_source/). (side note: I'm enjoying how easily people add _yet more tools_ to their development stack: npm, yarn, _and_ grunt?) This is all installed to /opt/grafana.

I had a Python install ready to go, but I'm going to try to build the Go stack in the same GOPATH of /opt/grafana to minimize resource usage on this machine.

**Comment by arodland** [comment]
Last time I tried it you did need zipper for a single-server install even though the zipper and carbonserver apis are almost identical. That might have changed with the recent globbing changes and pb3 though, so it's worth giving it a quick try to see if it works with one less moving part.

@zdykstra, hi, Doug is getting me set up so I can lend a hand, and it seems like we were thinking along very similar lines because I told him to skip the python and I would install zipper stack, within minutes of you saying the same. I run it at work, and I've contributed to carbonapi a bit :)

**Comment by preaction** [comment]
The Grafana install requires some NPM stuff, but it doesn't work on OpenBSD as-is: The `--pure-lockfile` argument to `yarn install` seems to lock it up.

It also seems to want PhantomJS (why), which I had to install manually. But that doesn't matter because Grafana expects it to be installed via the prebuilt binaries and not via any other way that works. When that failed, I removed the `phantomjs` task from the `default` Grunt task in `tasks/default_task.js`.

Node Sass complains about an unsupported platform (`Unsupported platform (openbsd) 64-bit with Node.js 4.x`), which to me defeats the entire purpose of having a virtual machine, but okay. Grunt told me to add `--force`, so I did. It didn't work though, as trying to start up grafana-server dies with `CRIT[03-17|17:56:50] Failed to detect generated css or javascript files in static root (/opt/grafana/src/github.com/grafana/grafana/public), have you executed default grunt task?%!(EXTRA []interface {}=[])`

The revised front-end install script is:

```
npm install -g yarn
npm install -g phantomjs
npm install phantomjs # Set up local symlinks that for some reason are expected...
yarn install
npm install -g grunt-cli
grunt --force
```

**Comment by arodland** [comment]
The purpose of PhantomJS is to render graphs that get sent along with alerts.

**Comment by preaction** [comment]
So I need to build libsass from source, which requires installing a recent enough version of g++, and that's where I stopped and am rebuilding it as a Debian 8 box. Then we'll start this again...

**Comment by arodland** [comment]
I tested — you can indeed point carbonapi directly at go-carbon's carbonserver and it will work, even with globs. So it's possible to get by with just those two pieces if you only have a single carbon box.

**Comment by preaction** [comment]
To try to get some more useful statistics and metrics out of the monitoring server, I'm going to try using InfluxDB instead of Graphite. To ship logs into the InfluxDB, I'm going to use Fluentd on the monitoring server to accept syslog from rsyslog on all the other servers. I'm trying InfluxDB because the tagging will allow for some richer queries, which may serve us better in the long-term. I picked InfluxDB over Prometheus because Prometheus seems to be pull-oriented, which is better for monitoring, but it seems like either would work because fluent...

So I'm considering, for now, these decisions made and I'll make some other tickets for getting all the logs shipped over (application and apache), setting up some apache and mysql monitoring, adding some backend health checks, and creating some useful application statistics.
