### ISSUE TITLE
is Rexfile.old required?

### ISSUE THREAD

**Issue by glasswalk3r** [cpan-testers/cpantesters-deploy#4]
Started checking the project right now, so please consider my lack of background...

I noticed that we have two Rexfiles in the repository:

  * Rexfile
  * Rexfile.old

Is the old one still needed? I couldn't find anything with `git log` about, but it seems the new Rexfile has all the things from the old one and more.

Can we get rid of it?

**Comment by preaction** [comment]
`Rexfile.old` has all the things I wrote to deploy the old backend and which need to be moved to the cpantesters-backend repository and updated to handle that repository's "old" directory. I haven't done that yet, as I've not needed to deploy those things, but I don't want to forget about this file by deleting it and leaving it only in the git history.
